### ISSUE TITLE
[BUG] Default evaluation type for default BurstPattern() method is Numeric Limit instead of Pass/Fail

### ISSUE THREAD

**Issue by SAntonya-NI** [ni/semi-test-library-dotnet#150]
This is minor one. The evaluation type for BurstPattern is Numeric Limit but should be Pass/Fail which force to error.
Would be great to fix this.
![image](https://github.com/user-attachments/assets/cd4c05b3-7bc8-4eba-85ad-88bfabe96744)

**Comment by SAntonya-NI** [comment]
@lornazh @Mattjet27 FYI

**Comment by Mattjet27** [comment]
@SAntonya-NI, thank you for reporting this bug. Please note that this issue is not directly related to the [semi-test-library-dotnet](https://github.com/ni/semi-test-library-dotnet) project source. Rather, it is specific to the deployment of the TestStandSteps as they get integrated into TestStand as Step Types and installed by the STS Software bundle. Nevertheless, I have relayed this issue internally to the appropriate team to have it addressed in the next release of the STS Software bundle.
